In [3]:
import numpy as np
np.random.seed(7)
cities = np.array(["Kathmandu", "Pokhara", "Biratnagar", "Lalitpur", "Birgunj"])
days = np.array([f"D{i:02d}" for i in range(1, 15)])
temps = np.random.randint(14, 36, size=(5, 14)).astype(float) # °C, 5 cities × 14 days
humidity = np.random.randint(40, 95, size=(5, 14)).astype(float) # %
temps[2, 5] = np.nan # sensor outage
temps[4, 11] = np.nan

## B1 — Array anatomy and reshaping

In [2]:
print("B1a - temps shape:", temps.shape)
print("B1b - temps dimension:", temps.ndim)
print("B1c - temps data type:", temps.dtype)
print("B1d - temps size:", temps.size)

B1a - temps shape: (5, 14)
B1b - temps dimension: 2
B1c - temps data type: float64
B1d - temps size: 70


In [4]:
nums = np.arange(70)

In [10]:
reshaped_explicit = nums.reshape(5, 14)
reshaped_a = nums.reshape(5, -1)

print("B1e - Reshaped with explicit dimensions:", reshaped_explicit)
print("\nB1f - Reshaped using -1:", reshaped_a)

print("\nB1g - Two results identical:", np.array_equal(reshaped_explicit, reshaped_a))

B1e - Reshaped with explicit dimensions: [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63 64 65 66 67 68 69]]

B1f - Reshaped using -1: [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63 64 65 66 67 68 69]]

B1g - Two results identical: True


In [8]:
flattened = reshaped_explicit.flatten()
print("B1h - Flattened array:", flattened)

B1h - Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [9]:
# -1 lets NumPy finds out the missing dimension automatically.
# Reshaping does not copy the data as it changes the way we view the data

## B2 — Indexing and slicing

In [12]:
pokhara_day3 = temps[1, 2]
print("B2a - Pokhara's day-3 temperature:", pokhara_day3)
print("Shape:", pokhara_day3.shape)

B2a - Pokhara's day-3 temperature: 14.0
Shape: ()


In [13]:
last_day = temps[:, -1]
print("B2b - Every city's reading on the last day:", last_day)
print("Shape:", last_day.shape)

B2b - Every city's reading on the last day: [30. 28. 21. 18. 30.]
Shape: (5,)


In [14]:
biratnagar = temps[2, :]
print("B2c - Biratnagar's full fortnight:", biratnagar)
print("Shape:", biratnagar.shape)

B2c - Biratnagar's full fortnight: [20. 18. 28. 23. 17. nan 22. 33. 30. 15. 14. 30. 26. 21.]
Shape: (14,)


In [16]:
first_three_days = temps[:3, 3:8]
print("B2d - First three cities across days 4-8:")
print(first_three_days)
print("Shape:", first_three_days.shape)

B2d - First three cities across days 4-8:
[[33. 21. 28. 22. 28.]
 [25. 20. 33. 26. 19.]
 [23. 17. nan 22. 33.]]
Shape: (3, 5)


In [17]:
lalitpur = temps[3, ::2]
print("B2e - Every other day for Lalitpur:", lalitpur)
print("Shape:", lalitpur.shape)

B2e - Every other day for Lalitpur: [24. 17. 21. 35. 17. 17. 33.]
Shape: (7,)


In [18]:
kathmandu_reversed = temps[0, ::-1]
print("B2f - Kathmandu's fortnight reversed:", kathmandu_reversed)
print("Shape:", kathmandu_reversed.shape)

B2f - Kathmandu's fortnight reversed: [30. 18. 20. 21. 22. 24. 28. 22. 28. 21. 33. 17. 18. 29.]
Shape: (14,)


## B3 — Boolean masks

In [19]:
mask = temps > 30

print("B3a - Readings above 30 per city:", np.sum(mask, axis=1))

kathmandu = temps[0] > 30
print("B3b - Kathmandu days above 30:", days[kathmandu])

B3a - Readings above 30 per city: [1 2 1 2 6]
B3b - Kathmandu days above 30: ['D04']


In [20]:
# A mask is a Boolean array that selects elements based on a condition.
# temps[temps > 30] cannot keep the 2D shape because it returns only matching values and original 2D shape is lost.

## B4 — Views vs. copies

In [32]:
kathmandu = temps[0, :3]
print("B4 - Original array:", temps)

B4 - Original array: [[20. 18. 17. 33. 21. 28. 22. 28. 24. 22. 21. 20. 18. 30.]
 [21. 26. 14. 25. 20. 33. 26. 19. 35. 30. 14. 16. 23. 28.]
 [20. 18. 28. 23. 17. nan 22. 33. 30. 15. 14. 30. 26. 21.]
 [24. 23. 17. 14. 21. 14. 35. 18. 17. 15. 17. 15. 33. 18.]
 [33. 15. 19. 23. 31. 16. 33. 32. 32. 35. 17. nan 29. 30.]]


In [33]:
kathmandu[0] = 999
print("B4 - Original array after modifying the slice:", temps)

B4 - Original array after modifying the slice: [[999.  18.  17.  33.  21.  28.  22.  28.  24.  22.  21.  20.  18.  30.]
 [ 21.  26.  14.  25.  20.  33.  26.  19.  35.  30.  14.  16.  23.  28.]
 [ 20.  18.  28.  23.  17.  nan  22.  33.  30.  15.  14.  30.  26.  21.]
 [ 24.  23.  17.  14.  21.  14.  35.  18.  17.  15.  17.  15.  33.  18.]
 [ 33.  15.  19.  23.  31.  16.  33.  32.  32.  35.  17.  nan  29.  30.]]


In [34]:
kathmandu_copy = temps[0, :3].copy()
original_value = kathmandu_copy[0]
kathmandu_copy[0] = 99
print("B4 - Original array after modifying the copy:", temps)

B4 - Original array after modifying the copy: [[999.  18.  17.  33.  21.  28.  22.  28.  24.  22.  21.  20.  18.  30.]
 [ 21.  26.  14.  25.  20.  33.  26.  19.  35.  30.  14.  16.  23.  28.]
 [ 20.  18.  28.  23.  17.  nan  22.  33.  30.  15.  14.  30.  26.  21.]
 [ 24.  23.  17.  14.  21.  14.  35.  18.  17.  15.  17.  15.  33.  18.]
 [ 33.  15.  19.  23.  31.  16.  33.  32.  32.  35.  17.  nan  29.  30.]]


In [35]:
# Slicing creates a view to avoid copying data.
# Without .copy(), changing the slice can change the original array.

## B5 — Vectorization vs. Python loop

In [36]:
temps[0, 0] = 20
print(temps[0, :3])

[20. 18. 17.]


In [19]:
import time

temps_loop = np.empty_like(temps)
rows, cols = temps.shape
for r in range(rows):
    for c in range(cols):
        temps_loop[r, c] = (temps[r,c] * 9 / 5) + 32

temps_vector = (temps * 9 / 5) + 32
print("B5a - Vectorized and loop results match:", np.allclose(temps_loop, temps_vector, equal_nan=True))

large_arr = np.random.randint(14, 26, size = 1_000_000).astype(float)

t0 = time.perf_counter()
large_loop = [x * 9 / 5 + 32 for x in large_arr]
t_loop = time.perf_counter() - t0

t0 = time.perf_counter()
large_vector = (large_arr * 9 / 5) + 32
t_vector = time.perf_counter() - t0

speedup = t_loop / t_vector

print(f"B5b - Loop time: {t_loop:.5f}s")
print(f"B5b - Vectorized time: {t_vector:.5f}s")
print(f"B5b - Vectorized code is roughly {speedup:.2f}x faster")

# The loop takes extra time for repeated Python-level iteration, indexing, and assignment.

B5a - Vectorized and loop results match: True
B5b - Loop time: 0.25582s
B5b - Vectorized time: 0.01197s
B5b - Vectorized code is roughly 21.38x faster


## B6 — Broadcasting

In [9]:
city_avg = np.nanmean(temps, axis=1, keepdims=True)

anomalies = temps - city_avg

print("B6a - Anomaly shape:", anomalies.shape)
print("B6a - Confirm shape (5, 14)?", anomalies.shape == (5, 14))

sensor_correction = np.array([
    0.2, -0.1, 0.3, 0.0, -0.2, 0.1, 0.2,
    -0.1, 0.0, 0.3, -0.2, 0.1, 0.0, -0.1
])

corrected_temps = temps + sensor_correction

print("\nB6b - Corrected temps shape:", corrected_temps.shape)
print("B6b - Corrected temperatures:", np.round(corrected_temps[:2, :4], 2))

try:
    wrong_result = temps + np.array([1, 2, 3, 4, 5])
except ValueError as e:
    print("\nB6c - ValueError:", e)

# Broadcasting aligns shapes from the right, so (14,) matches (5, 14) in (b), but (5,) does not in (c) causing dimension mismatch.

B6a - Anomaly shape: (5, 14)
B6a - Confirm shape (5, 14)? True

B6b - Corrected temps shape: (5, 14)
B6b - Corrected temperatures: [[29.2 17.9 17.3 33. ]
 [21.2 25.9 14.3 25. ]]

B6c - ValueError: operands could not be broadcast together with shapes (5,14) (5,) 


## B7 — Matrix multiplication

In [12]:
quantities = np.array([2, 3, 1])
prices = np.array([120, 90, 250])

print("B7a - quantities * prices:", quantities * prices)
print("B7a - quantities @ prices:", quantities @ prices)

mean_temp_per_day = np.nanmean(temps, axis=0)
mean_humidity_per_day = np.nanmean(humidity, axis=0)

features = np.column_stack((mean_temp_per_day, mean_humidity_per_day))

weights = np.array([0.6, -0.1])

comfort_score = features @ weights

print("\nB7b - Features shape:", features.shape)
print("B7b - Weights shape:", weights.shape)
print("B7b - Comfort score shape:", comfort_score.shape)
print("B7b - Daily comfort scores:", np.round(comfort_score, 2))

# * multiplies corresponding elements, while @ calculates the dot product.
# The inner dimensions must match so each feature can be multiplied by its corresponding weight.

B7a - quantities * prices: [240 270 250]
B7a - quantities @ prices: 760

B7b - Features shape: (14, 2)
B7b - Weights shape: (2,)
B7b - Comfort score shape: (14,)
B7b - Daily comfort scores: [ 9.06  5.32  4.16  6.58  5.06  6.39  9.16  8.74 11.26  7.22  2.6   6.43
  8.66  8.16]


## B8 — Aggregating along an axis

In [13]:
city_mean = np.nanmean(temps, axis=1)
city_max = np.nanmax(temps, axis=1)
city_min = np.nanmin(temps, axis=1)
city_std = np.nanstd(temps, axis=1)

print("B8a - Mean per city:", city_mean)
print("Shape:", city_mean.shape)

print("B8a - Max per city:", city_max)
print("Shape:", city_max.shape)

print("B8a - Min per city:", city_min)
print("Shape:", city_min.shape)

print("B8a - Std per city:", city_std)
print("Shape:", city_std.shape)

day_mean = np.nanmean(temps, axis=0)
day_max = np.nanmax(temps, axis=0)

print("\nB8b - Mean per day:", day_mean)
print("Shape:", day_mean.shape)

print("B8b - Max per day:", day_max)
print("Shape:", day_max.shape)

hottest_day_index = np.nanargmax(temps, axis=1)
hottest_days = days[hottest_day_index]

print("\nB8c - Hottest day for each city:", hottest_days)
print("Shape:", hottest_days.shape)

# axis=0 collapses the cities, while axis=1 collapses the days.

B8a - Mean per city: [23.64285714 23.57142857 22.84615385 20.07142857 26.53846154]
Shape: (5,)
B8a - Max per city: [33. 35. 33. 35. 35.]
Shape: (5,)
B8a - Min per city: [17. 14. 14. 14. 15.]
Shape: (5,)
B8a - Std per city: [4.89324816 6.41108733 5.89453663 6.41943796 7.11028924]
Shape: (5,)

B8b - Mean per day: [25.4  20.   19.   23.6  22.   22.75 27.6  26.   27.6  23.4  16.6  20.25
 25.8  25.4 ]
Shape: (14,)
B8b - Max per day: [33. 26. 28. 33. 31. 33. 35. 33. 35. 35. 21. 30. 33. 30.]
Shape: (14,)

B8c - Hottest day for each city: ['D04' 'D09' 'D08' 'D07' 'D10']
Shape: (5,)


## B9 — Reproducible randomness and a train/test split

In [14]:
flat_temps = temps.flatten()
np.random.seed(42)
indices = np.arange(len(flat_temps))
np.random.shuffle(indices)

split = int(0.8 * len(indices))
train_index = indices[:split]
test_index = indices[split:]

print("B9a - Train shape:", train_index.shape)
print("B9a - Test Shape:", test_index.shape)
print("B9a - Total samples sum to 70:", len(train_index) + len(test_index) == 70)
print("B9a - Share no index:", len(np.intersect1d(train_index, test_index)) == 0)

np.random.seed(42)
again = np.arange(len(flat_temps))
np.random.shuffle(again)

train2 = again[:split]
test2 = again[split:]

assert np.array_equal(train_index, train2)
assert np.array_equal(test_index, test2)
print("\nB9b - Assert passed. Hence, the split is identical.")

# Shuffling mixes the samples before splitting, while the seed makes the same split repeatable.

B9a - Train shape: (56,)
B9a - Test Shape: (14,)
B9a - Total samples sum to 70: True
B9a - Share no index: True

B9b - Assert passed. Hence, the split is identical.


## B10 — np.where , argmax , argmin

In [16]:
label = np.where(temps > 30, "hot", np.where(temps >= 22, "mild", "cold"))
print("B10a - Label's grid shape:", label.shape)
print("B10a - Sample:", label[:2, :5]) 

scores = np.array([0.08, 0.62, 0.21, 0.09])
labels = np.array(["rain", "clear", "cloudy", "fog"])

predicted_class = labels[np.argmax(scores)]
print(f"\nB10b- Predicted label: {predicted_class}")

# A classifier needs argmax to get the position of the highest score and select its corresponding label.
# max() returns only the float score instead of the label index.

B10a - Label's grid shape: (5, 14)
B10a - Sample: [['mild' 'cold' 'cold' 'hot' 'cold']
 ['cold' 'mild' 'cold' 'mild' 'cold']]

B10b- Predicted label: clear
